name: 'dbt_cloud_job_example_repo'
version: '1.0.0'
config-version: 2

profile: 'dbt_cloud_job_example_repo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.7.0", "<1.8.0"]

models:
  dbt_cloud_job_example_repo:
